services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: always
    dns: # fix connection issues, jackett could not connect, deluge cant get ip
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /dev/net:/dev/net:z # tun device
      - vpnconfig:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network
      - 9118:9117 # Port for jackett
    command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: always
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - downloads:/downloads # downloads folder
      - delugeconfig:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: always
    network_mode: service:vpn
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - jackettconfig:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: always
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - sonarrconfig:/config # config files
      - tvs:/tv # tv shows folder
      - downloads:/downloads # download folder
    ports:
      - 8988:8989

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: always
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - radarrconfig:/config # config files
      - movies:/movies # movies folder
      - downloads:/downloads # download folder
    ports:
      - 7879:7878

  # Remove plex, host it in windows directly
  # plex-server:
  #   container_name: plex-server
  #   image: plexinc/pms-docker:latest
  #   restart: always
  #   environment:
  #     - TZ=${TZ} # timezone, defined in .env
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #   volumes:
  #     - plexconfig:/config # plex database
  #     - plextranscode:/transcode # temp transcoded files
  #     - tvs:/data/tvs # media library
  #     - movies:/data/movies # media library
  #   ports:
  #     - 32401:32400

volumes:
  vpnconfig:
  sonarrconfig:
  radarrconfig:
  jackettconfig:
  #plexconfig:
  #plextranscode:
  delugeconfig:
  downloads:
  tvs:
  movies: